### ISSUE TITLE
Add serial wire checking to the LEA6 GPS library

### ISSUE THREAD

**Issue by imciner2** [M2I-HABET/HABETOS#5]
Implement checking in the initialization function to determine if the serial wires between the GPS and the ChipKit are reversed/not connected.

**Comment by imciner2** [comment]
Rudimentary serial checking using a command-response framework was implemented in the LEA6 library. Should actually try to use the more robust method of sensing line level on the ChipKit's RX pin (it should be driven high by the GPS puck).

**Comment by matgyver** [comment]
Closing this out.
